spring.application.name                    = bookstore
#----------------------DB_SOURCE------------------------------------------------>
spring.database.driverClassName            = org.postgresql.Driver
spring.datasource.url                      = jdbc:postgresql://localhost:5432/${POSTGRES_DB_NAME}
spring.datasource.username                 = ${POSTGRES_USERNAME}
spring.datasource.password                 = ${POSTGRES_PASSWORD}
#----------------------HIBERNATE_CONFIG------------------------------------------------>
spring.jpa.hibernate.ddl-auto               = create-drop
spring.jpa.show-sql                         = true

logging.level.org.springframework.core.env  = DEBUG

#logging.level.org.springframework.security = TRACE
jwt.secret-key                              = ${JWT_SECRET_KEY}
spring.main.banner-mode                     = off
#JWT_SECRET_KEY = 8160B829AFB326934998B03A9EB2B542C29A755960CF4A37B1138C4AD8497E58
#---------------------------ACTUATORS--------------------------------------->
#management.endpoints.web.exposure.include  = *
##health                                   , beans
#management.endpoint.health.show-details    = always
#management.endpoint.health.show-components = always
#management.health.db.enabled               = true
#----------------------devtools------------------------------------------------->
#spring.devtools.restart.enabled            = false
#----------------------swagger-ui------------------------------------------------>
#springdoc.api-docs.enabled                 = true
#springdoc.swagger-ui.enabled               = true
#springdoc.swagger-ui.path                  = /swagger-ui.html
springdoc.override-with-generic-response    = false
#---------------------------------------------------------------------------------->