spring.application.name                    = bookstore
#----------------------DB_SOURCE------------------------------------------------>
spring.database.driverClassName            = org.postgresql.Driver
spring.datasource.url                      = jdbc:postgresql://localhost:5432/${POSTGRES_DB_NAME}
spring.datasource.username                 = ${POSTGRES_USERNAME}
spring.datasource.password                 = ${POSTGRES_PASSWORD}
spring.jpa.database-platform               = org.hibernate.dialect.PostgreSQLDialect
#----------------------HIBERNATE_CONFIG------------------------------------------------>
spring.jpa.hibernate.ddl-auto              = create-drop
spring.jpa.show-sql                        = true

#logging.level.org.springframework.security = TRACE
jwt.secret-key                             = ${JWT_SECRET_KEY}

spring.main.banner-mode=off
#---------------------------ACTUATORS--------------------------------------->
#management.endpoints.web.exposure.include= *
##health,beans
#management.endpoint.health.show-details=always
#management.endpoint.health.show-components=always
#management.health.db.enabled=true
#----------------------devtools------------------------------------------------->
#spring.devtools.restart.enabled=false
#----------------------swagger-ui------------------------------------------------>
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html
springdoc.override-with-generic-response=false
#---------------------------------------------------------------------------------->